### ISSUE TITLE
hew while trying to run it i get this error

### ISSUE THREAD

**Issue by Dhimant404** [yash-007/Yolo-v4-DeepSort#1]
raceback (most recent call last):
  File "object_tracker.py", line 208, in <module>
    main()
  File "object_tracker.py", line 190, in main
    print("FPS: {.2f}".format(fps))
AttributeError: 'float' object has no attribute '2f'

**Comment by theartificialguy** [comment]
Hi
Thank you for reaching out to us for your query.
According to latest docs on python
Trying using "{:.2f} ".format

**Comment by Dhimant404** [comment]
Thank you, it works!
